### ISSUE TITLE
Получение ключа через браузер

### ISSUE THREAD

**Issue by YamadaHideki** [Back1ng/iot-battery-limiter#1]
Почему получаете ключ через браузер, если можно получить внутри программы через HTTP запросы?

**Comment by Back1ng** [comment]
> 

Запускается браузер из-за необходимости прямого разрешения от пользователя. 
https://yandex.ru/dev/id/doc/ru/codes/code-and-token
Но если я чего-то не знаю, буду благодарен за информацию.

**Comment by YamadaHideki** [comment]
Ну да, походу его никак не получить. Меня единственное что смущает это постоянный заряд разряд батареи, вместо того чтоб просто работать от сети. Мне кажется батарея умрет оч быстро.

**Comment by Back1ng** [comment]
> Ну да, походу его никак не получить. Меня единственное что смущает это постоянный заряд разряд батареи, вместо того чтоб просто работать от сети. Мне кажется батарея умрет оч быстро.

Как раз таки нет есть несколько нюансов:
1. Батарея находится в идеальном состоянии, когда она находится в пределах 50-70 процентов. Это как новое устройство - оно же приходит с ~66 процентами.
2. Такую логику давно практикую с телефоном, хоть и разряжается он реже, но по ощущению аккумулятор как новый, так как мало изнашивается из-за его нахождении в идеальном диапазоне.

В своем роде - эксперимент, который я проверяю на себе. Пользуюсь я ноутбуком не очень часто, поэтому не вижу всю проблему.
